# Generated by Django 4.1.1 on 2022-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
