# Generated by Django 4.1.1 on 2022-11-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_store', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='outfit_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('dress_name', models.CharField(max_length=50)),
                ('dress', models.ImageField(upload_to='dresses/')),
            ],
        ),
        migrations.DeleteModel(
            name='store',
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
